//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.AdoModelEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Link
    {
        public int showId { get; set; }
        public string self { get; set; }
        public string previousepisode { get; set; }
        public string previousepisodename { get; set; }
    
        public virtual Show Show { get; set; }
    }
}
